# Site settings
title: GeoExamples
email: rveciana@gmail.com
description: Map creation with Python and D3js / JavaScript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geoexamples.com" # the base hostname & protocol for your site

image: images/manifest/512x512-icon.png
teaser: teaser.png
twitter_username: rveciana
github_username:  rveciana
linkedin_username:  rogerveciana

comments: True

author:
  name: Roger Veciana i Rovira

# Build settings
markdown: kramdown
github: [metadata]

# Manifest

manifest_name: GeoExamples
manifest_description: Map creation with Python and D3js / JavaScript
manifest_lang: en
manifest_background_color: "#fff"
manifest_short_name:
manifest_display: standalone